// face/src/bots.ts
/** Bots: operator-authored dsh agent presets under `bots/<id>/` (spec §2).
 *
 * A bot is a directory holding `agent.cordis.yml` (the composition dsh mounts),
 * `preset.yml` (display metadata dsh reads), `SOUL.md` (the persona SOURCE),
 * `skills/` (a dsh skill root) and `journal/` (the only directory the bot may
 * write, from its home). The face is the only writer: it copies `_template`,
 * writes the metadata and the soul, and RENDERS the composition so the persona
 * row's `text` is the soul's text - dsh's `!!js` cannot read a sibling file
 * (cordis-plugin-loader evaluates it in an ESM `new Function` with neither
 * `require` nor `__dirname`), so the YAML carries a derived copy and this
 * module keeps the two in step. Editing `SOUL.md` by hand reaches nothing
 * until `updateSoul` runs again (spec R4).
 *
 * `_template` is invisible to dsh (a leading underscore is outside the preset
 * grammar) and refused as an id here; `kairos` is the inert default preset
 * (`bots/kairos`), never a bot. Ids are dsh's grammar `[a-z0-9][a-z0-9-]*`.
 * @module
 */
import { cp, readdir, readFile, stat, writeFile } from "node:fs/promises";
import type { IncomingMessage, ServerResponse } from "node:http";
import { join } from "node:path";
import { dump, load } from "js-yaml";
import { isJsonBody, isTrustedDataRequest } from "./data.ts";
import { FORBIDDEN, HttpError, readBody } from "./http.ts";
import type { RouteRegistrar } from "./static.ts";

const BIN = "kairos-face";

export const TEMPLATE = "_template";
/** dsh-agent-presets' preset-id grammar, bounded to 64 code points. */
export const BOT_ID_RE = /^[a-z0-9][a-z0-9-]{0,63}$/;
/** Ids the grammar admits but the face refuses: the default preset is not a bot. */
export const RESERVED_IDS: ReadonlySet<string> = new Set(["kairos"]);
export const isBotId = (value: unknown): value is string =>
  typeof value === "string" && BOT_ID_RE.test(value) && !RESERVED_IDS.has(value);

/** Relative from `bots/<id>/` - the preset mount resolves a relative plugin
 *  path from the preset's own directory (dsh-agent-presets README). */
export const BOT_PLUGIN_RELATIVE = "../../face/plugins/bot.js";

/** What a voice keeps of Kairos's roster (spec §2.2.1): the shell, file read
 *  and edit, search, web, skills, the question tool, and the market-data reads
 *  of the alpaca-kit MCP server under whatever the operator named it. Absent
 *  by design: delegation (`subagent*`, `workflow`, `ralph`), goals and todos,
 *  background jobs, every `agent_<bin>`, and every order or account tool -
 *  `orders`, `place_order`, `cancel_order`. Names come from the tree the face
 *  boots (`tools.schemas()`, dumped 2026-09-07); `mcp__*__<raw>` expands
 *  against the live tree in the plugin. */
export const DEFAULT_ALLOW: readonly string[] = [
  "ask_user_question", "bash", "edit", "glob", "grep", "read", "read_image", "skill",
  "str_replace_editor", "web_search", "write",
  "mcp__*__earnings", "mcp__*__daily_bars", "mcp__*__calendar", "mcp__*__corp_actions",
  "mcp__*__market_snapshot", "mcp__*__screen", "mcp__*__breadth",
];

/** The persona a fresh copy carries until the form or `updateSoul` replaces it. */
export const TEMPLATE_SOUL =
  "You are <bot name>, a discussant on the operator's research workbench. You hold one stance and argue it " +
  "from evidence; you say plainly when the evidence is thin. You are a voice, not a hand: you write no " +
  "strategy conclusions and you never trade.";

const GENERATED_HEADER =
  "# GENERATED by the face (face/src/bots.ts renderComposition) - do not hand-edit.\n" +
  "# The persona row's text is SOUL.md's text; edit SOUL.md through the face so both move.\n";

export function renderComposition(opts: { soul: string; allow: readonly string[]; plugin?: string }): string {
  const rows = [
    { id: "bot", name: opts.plugin ?? BOT_PLUGIN_RELATIVE, config: { persona: opts.soul, allow: [...opts.allow] } },
    { id: "skills", name: "@deepseek-ai/dsh-skill-filesystem", config: { customSkillDirs: ["./skills"], includeDefaultRoots: false } },
  ];
  return GENERATED_HEADER + dump(rows, { lineWidth: -1, noRefs: true });
}

export function renderPresetMeta(name: string, description: string): string {
  return dump({ name, description }, { lineWidth: -1 });
}

/** The soul text a request may carry: non-empty, no `{{` (the prompt is a strict template). */
export function rejectSoul(soul: unknown): string {
  if (typeof soul !== "string" || soul.trim() === "") throw new HttpError(400, "soul must be a non-empty string");
  if (soul.includes("{{")) throw new HttpError(400, "soul must not contain '{{' - the system prompt is a strict template with no escape");
  return soul.trim();
}

export interface BotRow {
  id: string;
  name: string;
  description: string;
  dir: string;
  /** The bot's home session cwd - its journal, the one directory it may write. */
  homeCwd: string;
  soul: string;
  /** `kairos`: the host composition, not a bot. */
  isDefault: boolean;
  /** dsh's own reason when the composition cannot mount (Rule 5: shown, never skipped). */
  broken?: string;
  /** false when the directory is here but the preset roster did not report it. */
  listed: boolean;
}

export type PresetLister = () => Promise<{ id: string; broken?: string }[]>;

/** Lowercase ASCII, whitespace and `_` to `-`, everything outside the grammar dropped; `""` when nothing survives. */
export function proposeBotId(displayName: string): string {
  return displayName
    .normalize("NFKD")
    .toLowerCase()
    .replace(/[\s_]+/g, "-")
    .replace(/[^a-z0-9-]/g, "")
    .replace(/-+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 64);
}

async function exists(path: string): Promise<boolean> {
  try { await stat(path); return true; } catch { return false; }
}

async function readMeta(dir: string): Promise<{ name?: string; description?: string }> {
  try {
    const parsed: unknown = load(await readFile(join(dir, "preset.yml"), "utf8"));
    if (parsed === null || typeof parsed !== "object") return {};
    const { name, description } = parsed as { name?: unknown; description?: unknown };
    return { ...(typeof name === "string" ? { name } : {}), ...(typeof description === "string" ? { description } : {}) };
  } catch { return {}; }
}

async function rowFor(root: string, id: string, presets: Map<string, { broken?: string }>): Promise<BotRow> {
  const dir = join(root, id);
  const meta = await readMeta(dir);
  const soul = await readFile(join(dir, "SOUL.md"), "utf8").then((s) => s.trim()).catch(() => "");
  const preset = presets.get(id);
  return {
    id, name: meta.name ?? id, description: meta.description ?? "", dir, homeCwd: join(dir, "journal"), soul,
    isDefault: id === "kairos",
    ...(preset?.broken === undefined ? {} : { broken: preset.broken }),
    listed: preset !== undefined,
  };
}

/** Every directory under `bots/` in the grammar, with dsh's view of it merged in. */
export async function listBots(root: string, presets: PresetLister): Promise<BotRow[]> {
  let entries: import("node:fs").Dirent[] = [];
  try {
    entries = await readdir(root, { withFileTypes: true });
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
    return [];
  }
  const reported = new Map((await presets()).map((p) => [p.id, p] as const));
  const ids = entries
    .filter((e) => e.isDirectory() && BOT_ID_RE.test(e.name))
    .map((e) => e.name)
    .sort((a, b) => a.localeCompare(b));
  return Promise.all(ids.map((id) => rowFor(root, id, reported)));
}

/** Birth `bots/<id>` from the template. Refuses a malformed or reserved id, a
 *  taken id, a templated soul and a missing template - never overwrites. */
export async function createBot(root: string, body: Record<string, unknown>): Promise<BotRow> {
  const name = typeof body.name === "string" && body.name.trim() !== "" ? body.name.trim() : undefined;
  const id = body.id !== undefined ? body.id : (name === undefined ? undefined : proposeBotId(name));
  if (!isBotId(id)) {
    throw new HttpError(400, "invalid bot id (lowercase letters, digits and -; starts with a letter or digit; up to 64; not kairos or _template)");
  }
  const description = typeof body.description === "string" ? body.description.trim() : "";
  const soul = body.soul === undefined ? TEMPLATE_SOUL : rejectSoul(body.soul);
  const template = join(root, TEMPLATE);
  if (!(await exists(join(template, "agent.cordis.yml")))) throw new HttpError(500, `bots/${TEMPLATE} missing`);
  const dir = join(root, id);
  if (await exists(dir)) throw new HttpError(409, "bot already exists");
  await cp(template, dir, { recursive: true, filter: (src) => !src.includes("__pycache__") });
  await writeFile(join(dir, "preset.yml"), renderPresetMeta(name ?? id, description), "utf8");
  await writeFile(join(dir, "SOUL.md"), `${soul}\n`, "utf8");
  await writeFile(join(dir, "agent.cordis.yml"), renderComposition({ soul, allow: DEFAULT_ALLOW }), "utf8");
  return rowFor(root, id, new Map());
}

/** Rewrite `SOUL.md` AND the composition's persona row - the two must never drift (spec R4). */
export async function updateSoul(root: string, id: unknown, soul: unknown): Promise<BotRow> {
  if (!isBotId(id)) throw new HttpError(400, "invalid bot id");
  const text = rejectSoul(soul);
  const dir = join(root, id);
  if (!(await exists(join(dir, "agent.cordis.yml")))) throw new HttpError(404, "no such bot");
  // A composition too broken for js-yaml is exactly the one the operator is here to repair
  // (Rule 5 lists it): read it for the mask if it parses, otherwise regenerate from DEFAULT_ALLOW.
  const raw = await readFile(join(dir, "agent.cordis.yml"), "utf8");
  type MaskRows = { id?: string; config?: { allow?: unknown } }[] | null;
  let current: MaskRows = null;
  try { current = load(raw) as MaskRows; } catch { current = null; }
  const allowRow = Array.isArray(current) ? current.find((r) => r?.id === "bot") : undefined;
  const allow = Array.isArray(allowRow?.config?.allow) ? (allowRow!.config!.allow as string[]) : [...DEFAULT_ALLOW];
  await writeFile(join(dir, "SOUL.md"), `${text}\n`, "utf8");
  await writeFile(join(dir, "agent.cordis.yml"), renderComposition({ soul: text, allow }), "utf8");
  return rowFor(root, id, new Map());
}

export interface BotRouteDeps {
  /** The `bots/` root itself - the directory holding `_template` and every bot. */
  botsRoot: string;
  /** `ctx.agentPresets.list()`, narrowed - dsh's view of the roster, `broken` reasons included. */
  listPresets: PresetLister;
}

/** A soul is prose; the default 4 KiB body limit is for names and ids. */
const SOUL_BODY_LIMIT = 65_536;

export function registerBotRoutes(webServer: RouteRegistrar, deps: BotRouteDeps): void {
  const send = (res: ServerResponse, status: number, body: unknown): void => {
    res.writeHead(status, { "content-type": "application/json; charset=utf-8" });
    res.end(typeof body === "string" ? body : JSON.stringify(body));
  };
  const get = (read: () => Promise<object>) =>
    async (req: IncomingMessage, res: ServerResponse): Promise<void> => {
      if (!isTrustedDataRequest(req)) return send(res, 403, FORBIDDEN);
      try {
        return send(res, 200, { ok: true, ...(await read()) });
      } catch (err) {
        if (err instanceof HttpError) return send(res, err.status, { ok: false, error: err.message });
        console.error(`${BIN}: bots listing failed:`, err);
        return send(res, 500, { ok: false, error: "request failed" });
      }
    };
  const post = (limit: number, act: (body: Record<string, unknown>) => Promise<object>) =>
    async (req: IncomingMessage, res: ServerResponse): Promise<void> => {
      if (!isTrustedDataRequest(req)) return send(res, 403, FORBIDDEN);
      if (req.method !== "POST") return send(res, 405, { ok: false, error: "POST only" });
      if (!isJsonBody(req)) return send(res, 415, { ok: false, error: "application/json only" });
      try {
        let body: Record<string, unknown>;
        try {
          const parsed: unknown = JSON.parse(await readBody(req, limit));
          if (parsed === null || typeof parsed !== "object") throw new Error("not an object");
          body = parsed as Record<string, unknown>;
        } catch (err) {
          if (err instanceof HttpError) throw err;
          throw new HttpError(400, "body must be a JSON object");
        }
        return send(res, 200, { ok: true, ...(await act(body)) });
      } catch (err) {
        if (err instanceof HttpError) return send(res, err.status, { ok: false, error: err.message });
        console.error(`${BIN}: bots route failed:`, err);
        return send(res, 500, { ok: false, error: "request failed" });
      }
    };

  webServer.register({ kind: "exact", path: "/data/bots.json", handler: get(async () => ({ bots: await listBots(deps.botsRoot, deps.listPresets) })) });
  webServer.register({ kind: "exact", path: "/data/bots", handler: post(SOUL_BODY_LIMIT, async (body) => ({ bot: await createBot(deps.botsRoot, body) })) });
  webServer.register({ kind: "exact", path: "/data/bots/soul", handler: post(SOUL_BODY_LIMIT, async (body) => ({ bot: await updateSoul(deps.botsRoot, body.id, body.soul) })) });
}
