// face/tests/bots.test.ts
import test from "node:test";
import assert from "node:assert/strict";
import { mkdir, readFile, stat, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { load } from "js-yaml";
import { makeBotsRoot } from "./bots-fixture.ts";
import {
  BOT_PLUGIN_RELATIVE, DEFAULT_ALLOW, TEMPLATE_SOUL, createBot, isBotId, listBots, rejectSoul,
  renderComposition, renderPresetMeta, updateSoul,
} from "../src/bots.ts";
import { HttpError } from "../src/http.ts";

const noPresets = async () => [] as { id: string; broken?: string }[];

test("isBotId is dsh's preset grammar minus the two names the face reserves", () => {
  for (const ok of ["buffett", "a", "spec-2", "x".repeat(64)]) assert.equal(isBotId(ok), true, ok);
  for (const bad of ["", "Buffett", "_template", "kairos", "-lead", "a_b", "a.b", "a b", "巴菲特", "x".repeat(65), 42, null]) {
    assert.equal(isBotId(bad), false, JSON.stringify(bad));
  }
});

test("rejectSoul refuses an empty or templated persona and returns the trimmed text", () => {
  assert.equal(rejectSoul("  You are Probe.\n"), "You are Probe.");
  for (const bad of ["", "   ", "Hi {{model}}", 3, undefined]) {
    assert.throws(() => rejectSoul(bad), (err: HttpError) => err.status === 400, JSON.stringify(bad));
  }
});

test("renderComposition is parseable YAML naming the plugin by a relative path, the persona verbatim, and the allow list", () => {
  const text = renderComposition({ soul: "You are Probe: a test voice.\nSecond line.", allow: ["bash", "read"] });
  const rows = load(text) as { id: string; name: string; config: Record<string, unknown> }[];
  assert.deepEqual(rows.map((r) => r.id), ["bot", "skills"]);
  assert.equal(rows[0].name, BOT_PLUGIN_RELATIVE);
  assert.deepEqual(rows[0].config, { persona: "You are Probe: a test voice.\nSecond line.", allow: ["bash", "read"] });
  assert.equal(rows[1].name, "@deepseek-ai/dsh-skill-filesystem");
  assert.deepEqual(rows[1].config, { customSkillDirs: ["./skills"], includeDefaultRoots: false });
  assert.match(text, /^# GENERATED by the face/m);
});

test("the shipped template composition IS renderComposition(TEMPLATE_SOUL, DEFAULT_ALLOW) - they cannot drift", async () => {
  const root = await makeBotsRoot();
  const shipped = await readFile(join(root, "_template", "agent.cordis.yml"), "utf8");
  assert.equal(shipped, renderComposition({ soul: TEMPLATE_SOUL, allow: DEFAULT_ALLOW }));
});

test("DEFAULT_ALLOW names read and speak tools only - never orders, delegation, or another agent", () => {
  for (const forbidden of ["subagent", "subagent_fork", "workflow", "ralph", "create_goal", "todo_write", "mcp__*__place_order", "mcp__*__cancel_order", "mcp__*__orders"]) {
    assert.equal(DEFAULT_ALLOW.includes(forbidden), false, forbidden);
  }
  for (const kept of ["bash", "read", "grep", "glob", "edit", "write", "web_search", "skill", "ask_user_question", "mcp__*__daily_bars"]) {
    assert.equal(DEFAULT_ALLOW.includes(kept), true, kept);
  }
  assert.equal(DEFAULT_ALLOW.some((n) => n.startsWith("agent_")), false);
});

test("createBot copies the template, writes the three files, renders the composition, and refuses a second time", async () => {
  const root = await makeBotsRoot();
  const made = await createBot(root, { id: "probe", name: "Probe", description: "a test voice", soul: "You are Probe." });
  assert.equal(made.id, "probe");
  assert.equal(made.homeCwd, join(root, "probe", "journal"));
  await stat(join(root, "probe", "journal", "notes.md"));
  await stat(join(root, "probe", "skills", "README.md"));
  assert.equal(await readFile(join(root, "probe", "SOUL.md"), "utf8"), "You are Probe.\n");
  assert.equal(await readFile(join(root, "probe", "preset.yml"), "utf8"), renderPresetMeta("Probe", "a test voice"));
  const rows = load(await readFile(join(root, "probe", "agent.cordis.yml"), "utf8")) as { config: { persona: string } }[];
  assert.equal(rows[0].config.persona, "You are Probe.");
  await assert.rejects(createBot(root, { id: "probe", name: "Probe" }), (err: HttpError) => err.status === 409);
});

test("createBot without a soul uses the template's, and proposes an id from the name when none is given", async () => {
  const root = await makeBotsRoot();
  const made = await createBot(root, { name: "Value Investor" });
  assert.equal(made.id, "value-investor");
  assert.equal(made.soul, TEMPLATE_SOUL);
  await assert.rejects(createBot(root, { name: "巴菲特型" }), (err: HttpError) => err.status === 400 && /id/.test(err.message));
});

test("createBot refuses bad ids, reserved ids, a templated soul, and a missing template", async () => {
  const root = await makeBotsRoot();
  for (const id of ["_template", "kairos", "Bad", "a b", "../x", "", 7]) {
    await assert.rejects(createBot(root, { id, name: "x" }), (err: HttpError) => err.status === 400, JSON.stringify(id));
  }
  await assert.rejects(createBot(root, { id: "ok", name: "x", soul: "{{cwd}}" }), (err: HttpError) => err.status === 400);
  const empty = join(root, "nowhere");
  await mkdir(empty);
  await assert.rejects(createBot(empty, { id: "ok", name: "x" }), (err: HttpError) => err.status === 500 && /_template/.test(err.message));
});

test("updateSoul rewrites SOUL.md and the composition's persona together, and 404s an unknown bot", async () => {
  const root = await makeBotsRoot();
  await createBot(root, { id: "probe", name: "Probe", soul: "v1" });
  const after = await updateSoul(root, "probe", "v2 of Probe");
  assert.equal(after.soul, "v2 of Probe");
  assert.equal(await readFile(join(root, "probe", "SOUL.md"), "utf8"), "v2 of Probe\n");
  const rows = load(await readFile(join(root, "probe", "agent.cordis.yml"), "utf8")) as { config: { persona: string } }[];
  assert.equal(rows[0].config.persona, "v2 of Probe");
  await assert.rejects(updateSoul(root, "ghost", "x"), (err: HttpError) => err.status === 404);
  await assert.rejects(updateSoul(root, "probe", "{{"), (err: HttpError) => err.status === 400);
});

test("updateSoul regenerates a composition js-yaml cannot parse, instead of throwing the parser's error", async () => {
  const root = await makeBotsRoot();
  await createBot(root, { id: "probe", name: "Probe", soul: "v1" });
  await writeFile(join(root, "probe", "agent.cordis.yml"), "- id: bot\n  config: [\n");   // truncated: load() throws
  const after = await updateSoul(root, "probe", "repaired");
  assert.equal(after.soul, "repaired");
  assert.equal(await readFile(join(root, "probe", "SOUL.md"), "utf8"), "repaired\n");
  const rows = load(await readFile(join(root, "probe", "agent.cordis.yml"), "utf8")) as { config: { persona: string; allow: string[] } }[];
  assert.equal(rows.length, 2);
  assert.equal(rows[0].config.persona, "repaired");
  assert.deepEqual(rows[0].config.allow, [...DEFAULT_ALLOW]);
});

test("listBots reads every directory in the grammar, marks the default, carries dsh's broken reason, and flags a bot the roster does not report", async () => {
  const root = await makeBotsRoot();
  await createBot(root, { id: "probe", name: "Probe", description: "a test voice", soul: "You are Probe." });
  await mkdir(join(root, "cracked"));
  await writeFile(join(root, "cracked", "agent.cordis.yml"), "not: a list\n");
  await mkdir(join(root, "Skipped"));            // outside the grammar: not a preset, not listed
  const presets = async () => [{ id: "kairos" }, { id: "probe" }, { id: "cracked", broken: "composition is not a list" }];
  const bots = await listBots(root, presets);
  assert.deepEqual(bots.map((b) => b.id), ["cracked", "kairos", "probe"]);
  const byId = new Map(bots.map((b) => [b.id, b]));
  assert.equal(byId.get("kairos")!.isDefault, true);
  assert.equal(byId.get("probe")!.name, "Probe");
  assert.equal(byId.get("probe")!.soul, "You are Probe.");
  assert.equal(byId.get("cracked")!.broken, "composition is not a list");
  assert.equal(byId.get("cracked")!.name, "cracked");        // no preset.yml → id
  const unlisted = await listBots(root, noPresets);
  assert.equal(unlisted.find((b) => b.id === "probe")!.listed, false);
});
