// face/tests/bots.test.ts
import test from "node:test";
import assert from "node:assert/strict";
import { mkdir, readFile, stat, writeFile } from "node:fs/promises";
import type { IncomingMessage, ServerResponse } from "node:http";
import { join } from "node:path";
import { Readable } from "node:stream";
import { load } from "js-yaml";
import type { WebRoute } from "@deepseek-ai/dsh-host-webserver";
import { makeBotsRoot } from "./bots-fixture.ts";
import {
  BOT_PLUGIN_RELATIVE, DEFAULT_ALLOW, TEMPLATE_SOUL, createBot, isBotId, listBots,
  registerBotRoutes, rejectSoul, renderComposition, renderPresetMeta, updateSoul,
} from "../src/bots.ts";
import { HttpError } from "../src/http.ts";

const noPresets = async () => [] as { id: string; broken?: string }[];

test("isBotId is dsh's preset grammar minus the two names the face reserves", () => {
  for (const ok of ["buffett", "a", "spec-2", "x".repeat(64)]) assert.equal(isBotId(ok), true, ok);
  for (const bad of ["", "Buffett", "_template", "kairos", "-lead", "a_b", "a.b", "a b", "巴菲特", "x".repeat(65), 42, null]) {
    assert.equal(isBotId(bad), false, JSON.stringify(bad));
  }
});

test("rejectSoul refuses an empty or templated persona and returns the trimmed text", () => {
  assert.equal(rejectSoul("  You are Probe.\n"), "You are Probe.");
  for (const bad of ["", "   ", "Hi {{model}}", 3, undefined]) {
    assert.throws(() => rejectSoul(bad), (err: HttpError) => err.status === 400, JSON.stringify(bad));
  }
});

test("renderComposition is parseable YAML naming the plugin by a relative path, the persona verbatim, and the allow list", () => {
  const text = renderComposition({ soul: "You are Probe: a test voice.\nSecond line.", allow: ["bash", "read"] });
  const rows = load(text) as { id: string; name: string; config: Record<string, unknown> }[];
  assert.deepEqual(rows.map((r) => r.id), ["bot", "skills"]);
  assert.equal(rows[0].name, BOT_PLUGIN_RELATIVE);
  assert.deepEqual(rows[0].config, { persona: "You are Probe: a test voice.\nSecond line.", allow: ["bash", "read"] });
  assert.equal(rows[1].name, "@deepseek-ai/dsh-skill-filesystem");
  assert.deepEqual(rows[1].config, { customSkillDirs: ["./skills"], includeDefaultRoots: false });
  assert.match(text, /^# GENERATED by the face/m);
});

test("the shipped template composition IS renderComposition(TEMPLATE_SOUL, DEFAULT_ALLOW) - they cannot drift", async () => {
  const root = await makeBotsRoot();
  const shipped = await readFile(join(root, "_template", "agent.cordis.yml"), "utf8");
  assert.equal(shipped, renderComposition({ soul: TEMPLATE_SOUL, allow: DEFAULT_ALLOW }));
});

test("DEFAULT_ALLOW names read and speak tools only - never orders, delegation, or another agent", () => {
  for (const forbidden of ["subagent", "subagent_fork", "workflow", "ralph", "create_goal", "todo_write", "mcp__*__place_order", "mcp__*__cancel_order", "mcp__*__orders"]) {
    assert.equal(DEFAULT_ALLOW.includes(forbidden), false, forbidden);
  }
  for (const kept of ["bash", "read", "grep", "glob", "edit", "write", "web_search", "skill", "ask_user_question", "mcp__*__daily_bars"]) {
    assert.equal(DEFAULT_ALLOW.includes(kept), true, kept);
  }
  assert.equal(DEFAULT_ALLOW.some((n) => n.startsWith("agent_")), false);
});

test("createBot copies the template, writes the three files, renders the composition, and refuses a second time", async () => {
  const root = await makeBotsRoot();
  const made = await createBot(root, { id: "probe", name: "Probe", description: "a test voice", soul: "You are Probe." });
  assert.equal(made.id, "probe");
  assert.equal(made.homeCwd, join(root, "probe", "journal"));
  await stat(join(root, "probe", "journal", "notes.md"));
  await stat(join(root, "probe", "skills", "README.md"));
  assert.equal(await readFile(join(root, "probe", "SOUL.md"), "utf8"), "You are Probe.\n");
  assert.equal(await readFile(join(root, "probe", "preset.yml"), "utf8"), renderPresetMeta("Probe", "a test voice"));
  const rows = load(await readFile(join(root, "probe", "agent.cordis.yml"), "utf8")) as { config: { persona: string } }[];
  assert.equal(rows[0].config.persona, "You are Probe.");
  await assert.rejects(createBot(root, { id: "probe", name: "Probe" }), (err: HttpError) => err.status === 409);
});

test("createBot without a soul uses the template's, and proposes an id from the name when none is given", async () => {
  const root = await makeBotsRoot();
  const made = await createBot(root, { name: "Value Investor" });
  assert.equal(made.id, "value-investor");
  assert.equal(made.soul, TEMPLATE_SOUL);
  await assert.rejects(createBot(root, { name: "巴菲特型" }), (err: HttpError) => err.status === 400 && /id/.test(err.message));
});

test("createBot refuses bad ids, reserved ids, a templated soul, and a missing template", async () => {
  const root = await makeBotsRoot();
  for (const id of ["_template", "kairos", "Bad", "a b", "../x", "", 7]) {
    await assert.rejects(createBot(root, { id, name: "x" }), (err: HttpError) => err.status === 400, JSON.stringify(id));
  }
  await assert.rejects(createBot(root, { id: "ok", name: "x", soul: "{{cwd}}" }), (err: HttpError) => err.status === 400);
  const empty = join(root, "nowhere");
  await mkdir(empty);
  await assert.rejects(createBot(empty, { id: "ok", name: "x" }), (err: HttpError) => err.status === 500 && /_template/.test(err.message));
});

test("updateSoul rewrites SOUL.md and the composition's persona together, and 404s an unknown bot", async () => {
  const root = await makeBotsRoot();
  await createBot(root, { id: "probe", name: "Probe", soul: "v1" });
  const after = await updateSoul(root, "probe", "v2 of Probe");
  assert.equal(after.soul, "v2 of Probe");
  assert.equal(await readFile(join(root, "probe", "SOUL.md"), "utf8"), "v2 of Probe\n");
  const rows = load(await readFile(join(root, "probe", "agent.cordis.yml"), "utf8")) as { config: { persona: string } }[];
  assert.equal(rows[0].config.persona, "v2 of Probe");
  await assert.rejects(updateSoul(root, "ghost", "x"), (err: HttpError) => err.status === 404);
  await assert.rejects(updateSoul(root, "probe", "{{"), (err: HttpError) => err.status === 400);
});

test("updateSoul regenerates a composition js-yaml cannot parse, instead of throwing the parser's error", async () => {
  const root = await makeBotsRoot();
  await createBot(root, { id: "probe", name: "Probe", soul: "v1" });
  await writeFile(join(root, "probe", "agent.cordis.yml"), "- id: bot\n  config: [\n");   // truncated: load() throws
  const after = await updateSoul(root, "probe", "repaired");
  assert.equal(after.soul, "repaired");
  assert.equal(await readFile(join(root, "probe", "SOUL.md"), "utf8"), "repaired\n");
  const rows = load(await readFile(join(root, "probe", "agent.cordis.yml"), "utf8")) as { config: { persona: string; allow: string[] } }[];
  assert.equal(rows.length, 2);
  assert.equal(rows[0].config.persona, "repaired");
  assert.deepEqual(rows[0].config.allow, [...DEFAULT_ALLOW]);
});

test("listBots reads every directory in the grammar, marks the default, carries dsh's broken reason, and flags a bot the roster does not report", async () => {
  const root = await makeBotsRoot();
  await createBot(root, { id: "probe", name: "Probe", description: "a test voice", soul: "You are Probe." });
  await mkdir(join(root, "cracked"));
  await writeFile(join(root, "cracked", "agent.cordis.yml"), "not: a list\n");
  await mkdir(join(root, "Skipped"));            // outside the grammar: not a preset, not listed
  const presets = async () => [{ id: "kairos" }, { id: "probe" }, { id: "cracked", broken: "composition is not a list" }];
  const bots = await listBots(root, presets);
  assert.deepEqual(bots.map((b) => b.id), ["cracked", "kairos", "probe"]);
  const byId = new Map(bots.map((b) => [b.id, b]));
  assert.equal(byId.get("kairos")!.isDefault, true);
  assert.equal(byId.get("probe")!.name, "Probe");
  assert.equal(byId.get("probe")!.soul, "You are Probe.");
  assert.equal(byId.get("cracked")!.broken, "composition is not a list");
  assert.equal(byId.get("cracked")!.name, "cracked");        // no preset.yml → id
  const unlisted = await listBots(root, noPresets);
  assert.equal(unlisted.find((b) => b.id === "probe")!.listed, false);
});

function fakeRes(): { out: { status: number; body: string }; res: ServerResponse } {
  const out = { status: 0, body: "" };
  const res = {
    writeHead(status: number) { out.status = status; return res; },
    end(body?: string | Buffer) { out.body = String(body ?? ""); return res; },
  };
  return { out, res: res as unknown as ServerResponse };
}
function getReq(host = "127.0.0.1:3090", headers: Record<string, string> = {}): IncomingMessage {
  return { headers: { host, ...headers }, method: "GET" } as unknown as IncomingMessage;
}
function postReq(body: string, host = "127.0.0.1:3090", headers: Record<string, string> = {}): IncomingMessage {
  const req = Readable.from([Buffer.from(body)]) as unknown as IncomingMessage;
  (req as { headers: unknown }).headers = { host, "content-type": "application/json", ...headers };
  (req as { method: string }).method = "POST";
  return req;
}
function routesFor(root: string): Map<string, WebRoute> {
  const routes: WebRoute[] = [];
  registerBotRoutes({ register: (route) => routes.push(route) }, { botsRoot: root, listPresets: async () => [{ id: "kairos" }] });
  return new Map(routes.map((r) => [r.path, r]));
}

test("routes: exactly three, and the fence refuses a forged host, a cross-site fetch, and a foreign origin", async () => {
  const routes = routesFor(await makeBotsRoot());
  assert.deepEqual([...routes.keys()].sort(), ["/data/bots", "/data/bots.json", "/data/bots/soul"]);
  for (const req of [getReq("evil.example:3090"), getReq("127.0.0.1:3090", { "sec-fetch-site": "cross-site" }), getReq("127.0.0.1:3090", { origin: "http://evil.example" })]) {
    const r = fakeRes();
    await routes.get("/data/bots.json")!.handler(req, r.res);
    assert.equal(r.out.status, 403);
    assert.equal(r.out.body, '{"ok":false,"error":"forbidden"}');
  }
});

test("routes: the listing answers ok with every bot row", async () => {
  const root = await makeBotsRoot();
  await createBot(root, { id: "probe", name: "Probe" });
  const r = fakeRes();
  await routesFor(root).get("/data/bots.json")!.handler(getReq(), r.res);
  assert.equal(r.out.status, 200);
  const body = JSON.parse(r.out.body) as { ok: boolean; bots: { id: string; listed: boolean }[] };
  assert.equal(body.ok, true);
  assert.deepEqual(body.bots.map((b) => b.id), ["kairos", "probe"]);
  assert.equal(body.bots[1].listed, false); // the fake roster reports only kairos
});

test("routes: create is POST+JSON only, 400 on junk, 200 then 409", async () => {
  const root = await makeBotsRoot();
  const create = routesFor(root).get("/data/bots")!;
  const get = fakeRes(); await create.handler(getReq(), get.res); assert.equal(get.out.status, 405);
  const text = fakeRes(); await create.handler(postReq("{}", "127.0.0.1:3090", { "content-type": "text/plain" }), text.res); assert.equal(text.out.status, 415);
  const junk = fakeRes(); await create.handler(postReq("not json"), junk.res); assert.equal(junk.out.status, 400);
  const first = fakeRes(); await create.handler(postReq('{"name":"Probe","soul":"You are Probe."}'), first.res);
  assert.equal(first.out.status, 200);
  assert.equal((JSON.parse(first.out.body) as { bot: { id: string } }).bot.id, "probe");
  await stat(join(root, "probe", "agent.cordis.yml"));
  const again = fakeRes(); await create.handler(postReq('{"name":"Probe"}'), again.res); assert.equal(again.out.status, 409);
});

test("routes: soul update carries prose past the 4 KiB default limit and 404s an unknown bot", async () => {
  const root = await makeBotsRoot();
  await createBot(root, { id: "probe", name: "Probe" });
  const soul = routesFor(root).get("/data/bots/soul")!;
  const long = "You are Probe. " + "Argue from evidence. ".repeat(400); // ~8.6 KiB
  const ok = fakeRes(); await soul.handler(postReq(JSON.stringify({ id: "probe", soul: long })), ok.res);
  assert.equal(ok.out.status, 200);
  assert.equal(await readFile(join(root, "probe", "SOUL.md"), "utf8"), `${long.trim()}\n`);
  const missing = fakeRes(); await soul.handler(postReq('{"id":"ghost","soul":"x"}'), missing.res); assert.equal(missing.out.status, 404);
});
